<?php
require_once 'config.php';
requireAdmin();
$db = getDB();

$payrollId = (int)($_GET['id'] ?? 0);
if (!$payrollId) { setFlash('error', 'Invalid request.'); header('Location: ' . SITE_URL . '/payslips.php'); exit; }

// Fetch full payslip data
$stmt = $db->prepare("SELECT p.*, e.full_name, e.email, e.position, e.department, e.job_type, e.employee_id as emp_code, e.payment_method, e.bank_name FROM payroll p JOIN employees e ON e.id=p.employee_id WHERE p.id=?");
$stmt->execute([$payrollId]);
$p = $stmt->fetch();
if (!$p) { setFlash('error', 'Payslip not found.'); header('Location: ' . SITE_URL . '/payslips.php'); exit; }

$comms = $db->prepare("SELECT * FROM commissions WHERE employee_id=? AND month=?");
$comms->execute([$p['employee_id'], $p['month']]);
$comms = $comms->fetchAll();

$allows = $db->prepare("SELECT * FROM allowances WHERE employee_id=? AND month=?");
$allows->execute([$p['employee_id'], $p['month']]);
$allows = $allows->fetchAll();

// Settings
$companyName    = getSetting('company_name', SITE_NAME);
$companyEmail   = getSetting('company_email', '');
$companyAddress = getSetting('company_address', '');
$currencySymbol = getSetting('currency_symbol', 'Rs.');
$period         = date('F Y', strtotime($p['month'].'-01'));

function fm($amount) {
    global $currencySymbol;
    return $currencySymbol . ' ' . number_format((float)$amount, 2);
}

// Build HTML email body
ob_start();
?>
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 20px; color: #333; }
  .wrap { max-width: 620px; margin: 0 auto; background: #fff; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,.1); }
  .header { background: #1a1f2e; color: #fff; padding: 28px 32px; }
  .header h1 { margin: 0 0 4px; font-size: 22px; }
  .header p { margin: 0; opacity: .7; font-size: 13px; }
  .meta { background: #3b82f6; color: #fff; padding: 14px 32px; display: flex; justify-content: space-between; font-size: 13px; }
  .body { padding: 28px 32px; }
  .greeting { font-size: 15px; margin-bottom: 20px; color: #444; }
  .section { margin-bottom: 22px; }
  .section h3 { font-size: 12px; text-transform: uppercase; letter-spacing: .5px; color: #888; border-bottom: 1px solid #eee; padding-bottom: 6px; margin-bottom: 10px; }
  .row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; border-bottom: 1px solid #f5f5f5; }
  .row:last-child { border-bottom: none; }
  .row .label { color: #666; }
  .row .value { font-weight: 600; color: #222; }
  .row .deduct { color: #e53e3e; }
  .total-box { background: #f0fdf4; border: 2px solid #00c48c; border-radius: 8px; padding: 18px 24px; display: flex; justify-content: space-between; align-items: center; margin-top: 20px; }
  .total-label { font-size: 15px; font-weight: 700; color: #333; }
  .total-amount { font-size: 26px; font-weight: 800; color: #00c48c; }
  .status-paid { background: #00c48c; color: #fff; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700; }
  .status-pending { background: #f5a623; color: #fff; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 700; }
  .footer { background: #f8f8f8; padding: 18px 32px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; }
  .notice { background: #fff8e1; border-left: 4px solid #f5a623; padding: 12px 16px; border-radius: 4px; font-size: 13px; color: #666; margin-bottom: 20px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="header">
    <h1><?= htmlspecialchars($companyName) ?></h1>
    <p>Payslip for <?= $period ?></p>
  </div>
  <div class="meta">
    <span>📅 Period: <strong><?= $period ?></strong></span>
    <span>
      <?php if ($p['payment_status'] === 'paid'): ?>
        <span class="status-paid">✓ PAID</span>
      <?php else: ?>
        <span class="status-pending">⏳ PENDING</span>
      <?php endif; ?>
    </span>
  </div>
  <div class="body">
    <p class="greeting">Dear <strong><?= htmlspecialchars($p['full_name']) ?></strong>,<br>
    Please find your payslip for <strong><?= $period ?></strong> below.</p>

    <div class="notice">
      📌 This is an internal payslip generated by <?= htmlspecialchars($companyName) ?>. Please keep it confidential.
    </div>

    <!-- Employee Details -->
    <div class="section">
      <h3>Employee Details</h3>
      <div class="row"><span class="label">Employee ID</span><span class="value"><?= htmlspecialchars($p['emp_code']) ?></span></div>
      <div class="row"><span class="label">Position</span><span class="value"><?= htmlspecialchars($p['position']) ?></span></div>
      <div class="row"><span class="label">Department</span><span class="value"><?= htmlspecialchars($p['department']) ?></span></div>
      <div class="row"><span class="label">Job Type</span><span class="value"><?= ($p['job_type'] ?? '') === 'remote' ? '🌐 Remote Job' : '🏢 On-site Job' ?></span></div>
      <div class="row"><span class="label">Payment Method</span><span class="value"><?= ucwords(str_replace('_',' ',$p['payment_method'])) ?></span></div>
      <?php if ($p['bank_name']): ?>
      <div class="row"><span class="label">Bank</span><span class="value"><?= htmlspecialchars($p['bank_name']) ?></span></div>
      <?php endif; ?>
    </div>

    <!-- Earnings -->
    <div class="section">
      <h3>Earnings</h3>
      <div class="row"><span class="label">Base Salary</span><span class="value"><?= fm($p['base_salary']) ?></span></div>
      <?php if ($p['bonus'] > 0): ?>
      <div class="row"><span class="label">Bonus</span><span class="value"><?= fm($p['bonus']) ?></span></div>
      <?php endif; ?>
      <?php foreach ($allows as $a): ?>
      <div class="row"><span class="label"><?= ucfirst($a['allowance_type']) ?> Allowance</span><span class="value"><?= fm($a['amount']) ?></span></div>
      <?php endforeach; ?>
      <?php foreach ($comms as $c): ?>
      <div class="row"><span class="label">Commission: <?= htmlspecialchars($c['project_name']) ?></span><span class="value"><?= fm($c['commission_amount']) ?></span></div>
      <?php endforeach; ?>
    </div>

    <!-- Deductions -->
    <?php if ($p['deductions'] > 0 || $p['advance_payment'] > 0): ?>
    <div class="section">
      <h3>Deductions</h3>
      <?php if ($p['deductions'] > 0): ?>
      <div class="row"><span class="label">Deductions</span><span class="value deduct">-<?= fm($p['deductions']) ?></span></div>
      <?php endif; ?>
      <?php if ($p['advance_payment'] > 0): ?>
      <div class="row"><span class="label">Advance Recovery</span><span class="value deduct">-<?= fm($p['advance_payment']) ?></span></div>
      <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php if ($p['notes']): ?>
    <div class="section">
      <h3>Notes</h3>
      <p style="font-size:13px;color:#666;margin:0"><?= htmlspecialchars($p['notes']) ?></p>
    </div>
    <?php endif; ?>

    <!-- Net Total -->
    <div class="total-box">
      <span class="total-label">Net Salary</span>
      <span class="total-amount"><?= fm($p['final_salary']) ?></span>
    </div>
  </div>

  <div class="footer">
    <p><?= htmlspecialchars($companyName) ?><?= $companyAddress ? ' · ' . htmlspecialchars($companyAddress) : '' ?></p>
    <p style="margin-top:4px">This is a system-generated payslip. Please do not reply to this email.</p>
  </div>
</div>
</body>
</html>
<?php
$emailBody = ob_get_clean();

// Send email
$toEmail   = $p['email'];
$toName    = $p['full_name'];
$fromEmail = getSetting('email_from') ?: (getSetting('company_email') ?: 'payroll@creativelements.co');
$fromName  = $companyName;
$subject   = "Payslip for {$period} | {$companyName}";
$msgId     = '<' . time() . '.' . md5($toEmail) . '@creativelements.co>';

$headers  = "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/html; charset=UTF-8\r\n";
$headers .= "From: {$fromName} <{$fromEmail}>\r\n";
$ccEmail = getCCEmail();
if ($ccEmail) $headers .= "Cc: {$ccEmail}\r\n";
$headers .= "Reply-To: {$fromEmail}\r\n";
$headers .= "Return-Path: {$fromEmail}\r\n";
$headers .= "Message-ID: {$msgId}\r\n";
$headers .= "Date: " . date('r') . "\r\n";
$headers .= "X-Mailer: PHP/" . phpversion() . "\r\n";
$headers .= "X-Priority: 3\r\n";
$headers .= "X-MSMail-Priority: Normal\r\n";
$headers .= "Importance: Normal";

$params = "-f{$fromEmail}";
$sent = mail($toEmail, $subject, $emailBody, $headers, $params);

if ($sent) {
    try {
        $db->prepare("INSERT INTO payslip_emails (payroll_id, sent_to, sent_at) VALUES (?,?,NOW()) ON DUPLICATE KEY UPDATE sent_at=NOW()")
           ->execute([$payrollId, $toEmail]);
    } catch (Exception $e) { /* ignore */ }
    $ccNote = $ccEmail ? " (CC: {$ccEmail})" : '';
    setFlash('success', "✅ Payslip emailed to {$toName} ({$toEmail}){$ccNote}!");
} else {
    setFlash('error', "❌ Failed to send email to {$toEmail}. Check your cPanel email settings.");
}

header('Location: ' . SITE_URL . '/payslips.php?id=' . $payrollId . '&month=' . date('Y-m', strtotime($p['month'].'-01')));
exit;
